# Generated by Django 4.0.5 on 2022-06-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotel_records',
            fields=[
                ('id', models.AutoField(max_length=50, primary_key=True, serialize=False)),
                ('room_number', models.IntegerField(max_length=50)),
                ('amount_paid', models.IntegerField(max_length=1000000)),
                ('occupant_name', models.CharField(max_length=100)),
                ('occupant_emial', models.EmailField(max_length=50)),
                ('occupant_occupation', models.CharField(max_length=100)),
                ('number_of_night', models.IntegerField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
