# Generated by Django 4.0.5 on 2022-06-13 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel_records',
            old_name='occupant_emial',
            new_name='occupant_email',
        ),
    ]
