# Generated by Django 4.0.5 on 2022-06-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0002_rename_occupant_emial_hotel_records_occupant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_records',
            name='amount_paid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hotel_records',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hotel_records',
            name='number_of_night',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hotel_records',
            name='room_number',
            field=models.IntegerField(),
        ),
    ]
