# Generated by Django 4.0.5 on 2022-06-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0003_alter_hotel_records_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_records',
            name='amount_paid',
            field=models.IntegerField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='hotel_records',
            name='id',
            field=models.AutoField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hotel_records',
            name='number_of_night',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hotel_records',
            name='room_number',
            field=models.IntegerField(max_length=50),
        ),
    ]
