# Generated by Django 4.0.5 on 2022-06-15 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0004_alter_hotel_records_amount_paid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hotel_records',
            new_name='Record',
        ),
    ]
