# Generated by Django 4.0.5 on 2022-06-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0006_alter_record_end_date_alter_record_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='start_date',
            field=models.DateField(),
        ),
    ]
